export const SAMPLE_JD = `Position: Senior Full-Stack Software Engineer
Company: CloudSync Technologies
Location: San Francisco, CA (Hybrid)

About the Role:
We are looking for a Senior Full-Stack Software Engineer to join our core product team. You will be responsible for designing, building, and maintaining robust web applications, scaling our database architectures, and leading key technical projects. The ideal candidate has deep expertise in standard web technologies, a strong product mindset, and thrives in a fast-paced environment.

Key Responsibilities:
- Design, develop, and deploy scalable, responsive, and secure web applications.
- Build robust developer interfaces using React, TypeScript, and modern state management.
- Architect and optimize server-side REST/GraphQL APIs using Node.js and Express.
- Improve system performance, write comprehensive unit and integration tests, and establish CICD best practices.
- Mentor junior engineers, contribute to design RFCs, and collaborate closely with product managers and designers.

Required Experience & Skills:
- 5+ years of professional software engineering experience.
- Deep, hands-on experience with TypeScript, React, Node.js, and Express.
- Proficient in SQL (PostgreSQL) and database optimization.
- Experience with modern Cloud platforms (Google Cloud Platform or AWS) and containerization (Docker).
- Strong communication skills and experience leading technical projects or mentoring engineers.

Preferred Qualifications:
- Bachelor's or Master's degree in Computer Science, Engineering, or a related technical field.
- Experience building AI-powered features or integrating with LLM APIs (like Gemini or OpenAI).
- Advanced certifications in Google Cloud or AWS.`;

export const SAMPLE_RESUME_FILENAME = "john_doe_resume.pdf";

// A valid, ultra-compact basic PDF containing candidate profile, skills, education, and projects for John Doe.
export const SAMPLE_RESUME_BASE64 = "JVBERi0xLjQKMSAwIG9iagogIDw8IC9UeXBlIC9DYXRhbG9nIC9QYWdlcyAyIDAgUiA+PgplbmRvYmoKMiAwIG9iagogIDw8IC9UeXBlIC9QM2dlcyAvS2lkcyBbIDMgMCBSIF0gL0NvdW50IDEgPj4KZW5kb2JqCjMgMCBvYmogCiAgPDwgL1R5cGUgL1BhZ2UgL1BhcmVudCAyIDAgUiAvTWVkaWFCb3ggWyAwIDAgNTk1LjI3NSA4NDEuODg5IF0gL1Jlc291cmNlcyA8PCAvRm9udCA8PCAvRjEgNCAwIFIgPj4gPj4gL0NvbnRlbnRzIDUgMCBSID4+CmVuZG9iago0IDAgb2JqCiAgPDwgL1R5cGUgL0ZvbnQgL1N1YnR5cGUgL1R5cGUxIC9CYXNlRm9udCAvSGVsdmV0aWNhID4+CmVuZG9iago1IDAgb2JqCjw8IC9MZW5ndGggMzUwID4+CnN0cmVhbQpCVAovRjEgMTIgVGYKNzIgNzUwIFRkCihKb2huIERvZSAtIFNlbmlvciBGdWxsIFN0YWNrIEVuZ2luZWVyKSBUagowIC0xOCBUZChFbWFpbDogam9obi5kb2VAZXhhbXBsZS5jb20gfCBQaG9uZTogKzEgNTVVLTU1NS0wMTk4KSBUagowIC0xOCBUZChMaW5rZWRJbjogbGlua2VkaW4uY29tL2luL2pvaG5kb2UgfCBTYW4gRnJhbmNpc2NvLCBDQSkgVgoKMCAtMjQgVGQoUFJPRkVTU0lPTkFMLVNVTU1BUlkpIFRqCjAgLTEyIFRkKFBhc3Npb25hdGUgU2VuaW9yIEZ1bGwtU3RhY2sgRW5naW5lZXIgd2l0aCA4IHllYXJzIG9mIGV4cGVyaWVuY2UuKSBUagowIC0xMiBUZChTcGVjaWFsaXppbmcgaW4gUmVhY3QsIFR5cGVTY3JpcHQsIE5vZGUuanMsIGFuZCBoZWF2eSBTUUwvUG9zdGdyZVNRTCBvcHRpbWl6YXRpb24uKSBUagoKMCAtMjQgVGQoUFJPRkVTU0lPTkFMLUVYUEVSSUVOQ0UpIFRqCjAgLTEyIFRkKFNlbmlvciBTb2Z0d2FyZSBFbmdpbmVlciBhdCBHcm93dGhGbG93IEluYy4gfCAyMDIxIC0gUHJlc2VudCkgVGoKMCAtMTIgVGQoLSBMZWQgZGV2ZWxvcG1lbnQgb2YgY29yZSByZWFsLXRpbWUgYW5hbHl0aWNzIGRhc2hib2FyZCB1c2luZyBSZWFjdCBhbmQgVHlwZVNjcmlwdC4pIFRqCjAgLTEyIFRkKC0gT3B0aW1pemVkIFBvc3RncmVTUUwgZGF0YWJhc2UgcXVlcmllcywgcmVkdWNpbmcgcGFnZSBsb2FkIHRpbWVzIGJ5IDQ1JS4pIFRqCjAgLTEyIFRkKC0gTWVudG9yZWQgMyBqdW5pb3IgZGV2ZWxvcGVycyBhbmQgY28tYXV0aG9yZWQgMyBpbnRlcm5hbCB0ZWNoIHNwZWNzLikgVGoKMCAtMTggVGQoU29mdHdhcmUgRW5naW5lZXIgYXQgU2Fhc0NvbSB8IDIwMTggLTIwMjEpIFRqCjAgLTEyIFRkKC0gQnVpbHQgYW5kIG1haW50YWluZWQgTm9kZS5qcyBtaWNyb3NlcnZpY2VzIHdpdGggRXhwcmVzcy4gRGVwbG95ZWQgb24gR0NQLikgVGoKCjAgLTI0IFRkKEVEVUNBVElPTikgVGowIC0xMiBUZChCYWNoZWxvciBvZiBTY2llbmNlIGluIENvbXB1dGVyIFNjaWVuY2UgLSBTYW4gRnJhbmNpc2NvIFN0YXRlIFVuaXZlcnNpdHkpIFRqCgowIC0yNCBUZChQUk9KRUNUUykgVGowIC0xMiBUZChDby1Gb3VuZGVkIGFuIG9wZW4tc291cmNlIEFJIHJlc3VtZSBwYXJzZXIgYW5kIGdlbmVyYXRvciB1c2luZyBHZW1pbmkgQVBJLikgVGoKRVQKZW5kc3RyZWFtCmVuZG9iagp4cmVmCjAgNgowMDAwMDAwMDAwIDY1NTM1IGYgCjAwMDAwMDAwMTAgMDAwMDAgbiAKMDAwMDAwMDA1OSAwMDAwMCBuIAowMDAwMDAwMTIwIDAwMDAwIG4gCjAwMDAwMDAyNTcgMDAwMDAgbiAKMDAwMDAwMDMyOSAwMDAwMCBuIAp0cmFpbGVyCjw8IC9TaXplIDYgL1Jvb3QgMSAwIFIgPj4Kc3RhcnR4cmVmCjczOQolJUVPRg==";
